language: shell
os: windows
script:
 - cmd.exe /C '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x86 && MSBuild.exe WindowTeleport.sln -nologo -p:Configuration=Release -p:Platform=Win32'
